# Generated by Django 5.0 on 2024-08-24 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0004_alter_student_registration_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo de la Solicitud')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20, verbose_name='Estado de la solicitud')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Menu.student_registration')),
            ],
            options={
                'verbose_name': 'Solicitud de Constancia de Estudio',
                'verbose_name_plural': 'Solicitudes de Constancias de Estudio',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
