# Generated by Django 5.0 on 2024-07-24 23:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnf', models.CharField(choices=[('INFORMATICA', 'Informatica'), ('CONTADURIA', 'Contaduria'), ('ADMINISTRACION', 'Administracion')], default='INFORMATICA', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_seccion', models.IntegerField(choices=[(1000, 'Seccion 1000'), (1100, 'Seccion 1100'), (1200, 'Seccion 1200')], default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6'), (7, 'Semestre 7'), (8, 'Semestre 8')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('Mañana', 'Matutino'), ('Tarde', 'Vespertino'), ('Noche', 'Nocturno')], default='Mañana', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('s_nombre', models.CharField(max_length=30, verbose_name='Segundo Nombre')),
                ('p_apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('s_apellido', models.CharField(max_length=30, verbose_name='Segundo Apellido')),
                ('edad', models.IntegerField()),
                ('cedula', models.IntegerField(unique=True)),
                ('creado_en', models.DateField(default=django.utils.timezone.now)),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.carrera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.periodoacademico')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.seccion')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.semestre')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.turno')),
            ],
        ),
    ]
