# Generated by Django 5.0 on 2024-07-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='pnf',
            field=models.CharField(choices=[('INFORMATICA', 'Informatica'), ('CONTADURIA', 'Contaduria'), ('ADMINISTRACION', 'Administracion'), ('COMUNICACION SOCIAL', 'Comunicacion Social'), ('DISTRIBUCION Y LOGISTICA', 'Distribucion y Logistica')], default='INFORMATICA', max_length=24),
        ),
    ]
