# Generated by Django 5.0 on 2024-08-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='motivo_documento',
            field=models.FileField(blank=True, null=True, upload_to='motivos/'),
        ),
    ]
