# Generated by Django 5.0 on 2024-08-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_remove_constancia_motivo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constancia',
            name='motivo',
            field=models.TextField(verbose_name='Primera Solicitud'),
        ),
    ]
