# Generated by Django 5.0 on 2024-08-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_alter_constancia_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constancia',
            name='motivo',
        ),
        migrations.AddField(
            model_name='constancia',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
