# Generated by Django 5.0 on 2024-08-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0006_remove_constancia_verificado_constancia_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constancia',
            name='motivo',
        ),
        migrations.AddField(
            model_name='constancia',
            name='primera_solicitud',
            field=models.BooleanField(default=False, verbose_name='¿Primera Solicitud?'),
        ),
    ]
