# Generated by Django 4.2 on 2025-05-19 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnetestudiantil',
            name='expiracion',
            field=models.DateField(default=datetime.datetime(2026, 5, 19, 17, 14, 19, 509048, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Expiración'),
        ),
    ]
