# Generated by Django 4.2 on 2026-02-01 23:10

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnf', models.CharField(choices=[('INFORMATICA', 'Informatica'), ('CONTADURIA', 'Contaduria'), ('ADMINISTRACION', 'Administracion'), ('COMUNICACION SOCIAL', 'Comunicacion Social'), ('DISTRIBUCION Y LOGISTICA', 'Distribucion y Logistica')], default='INFORMATICA', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo Academico',
                'verbose_name_plural': 'Periodos Academicos',
            },
        ),
        migrations.CreateModel(
            name='RecuperacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud')),
                ('recuperado', models.BooleanField(default=False, verbose_name='Recuperado')),
            ],
            options={
                'verbose_name': 'Solicitud de Recuperacion',
                'verbose_name_plural': 'Solicitudes de Recuperacion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_seccion', models.IntegerField(choices=[(1000, 'Seccion 1000'), (1100, 'Seccion 1100'), (1200, 'Seccion 1200')], default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6'), (7, 'Semestre 7'), (8, 'Semestre 8')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estudiante', models.CharField(choices=[('Regular', 'Regular'), ('Nuevo Ingreso', 'Nuevo Ingreso')], default='Regular', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('Mañana', 'Matutino'), ('Tarde', 'Vespertino'), ('Noche', 'Nocturno')], default='Mañana', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('s_nombre', models.CharField(max_length=30, verbose_name='Segundo Nombre')),
                ('p_apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('s_apellido', models.CharField(max_length=30, verbose_name='Segundo Apellido')),
                ('edad', models.IntegerField()),
                ('cedula', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('creado_en', models.DateField(default=django.utils.timezone.now)),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.periodoacademico')),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.carrera')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.seccion')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.semestre')),
                ('tipo_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.tipoestudiante')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.turno')),
            ],
            options={
                'verbose_name': 'Estudiante Registrado',
                'verbose_name_plural': 'Estudiantes Registrados',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/usuario_defecto.jpg', upload_to='users/', verbose_name='Imagen de perfil')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Localidad')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('Foto Carnet', 'Foto Carnet'), ('Cédula', 'Cédula'), ('Notas Certificadas', 'Notas Certificadas'), ('Título', 'Título'), ('Partida de Nacimiento', 'Partida de Nacimiento')], max_length=25, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])], verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Menu.student_registration')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='CarnetEstudiantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carnet', models.CharField(max_length=20, unique=True, verbose_name='Número de Carnet')),
                ('codigo_barras', models.ImageField(upload_to='carnets/', verbose_name='Código de Barras')),
                ('emitido_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('expiracion', models.DateField(default=datetime.datetime(2027, 2, 1, 23, 10, 25, 224686, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Expiración')),
                ('pdf_carnet', models.FileField(blank=True, null=True, upload_to='carnets_pdf/', verbose_name='Carnet en PDF')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Menu.student_registration', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Carnet Estudiantil',
                'verbose_name_plural': 'Carnets Estudiantiles',
            },
        ),
    ]
