# Generated by Django 5.0 on 2024-08-21 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnf', models.CharField(choices=[('INFORMATICA', 'Informatica'), ('CONTADURIA', 'Contaduria'), ('ADMINISTRACION', 'Administracion'), ('COMUNICACION SOCIAL', 'Comunicacion Social'), ('DISTRIBUCION Y LOGISTICA', 'Distribucion y Logistica')], default='INFORMATICA', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_seccion', models.IntegerField(choices=[(1000, 'Seccion 1000'), (1100, 'Seccion 1100'), (1200, 'Seccion 1200')], default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6'), (7, 'Semestre 7'), (8, 'Semestre 8')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('Mañana', 'Matutino'), ('Tarde', 'Vespertino'), ('Noche', 'Nocturno')], default='Mañana', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/usuario_defecto.jpg', upload_to='users/', verbose_name='Imagen de perfil')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Localidad')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='student_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('s_nombre', models.CharField(max_length=30, verbose_name='Segundo Nombre')),
                ('p_apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('s_apellido', models.CharField(max_length=30, verbose_name='Segundo Apellido')),
                ('edad', models.IntegerField()),
                ('cedula', models.IntegerField(unique=True)),
                ('creado_en', models.DateField(default=django.utils.timezone.now)),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.periodoacademico')),
                ('pnf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.carrera')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.seccion')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.semestre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.turno')),
            ],
        ),
    ]
