# Generated by Django 5.0 on 2024-08-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_remove_student_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='correo',
            field=models.EmailField(default='default@example.com', max_length=150, verbose_name='Correo Electronico'),
            preserve_default=False,
        ),
    ]
