# Generated by Django 5.0 on 2024-08-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_student_registration_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico'),
        ),
    ]
