# Generated by Django 5.0 on 2024-08-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_student_registration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_registration',
            name='user',
        ),
    ]
