# Generated by Django 5.0 on 2024-08-30 21:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_recuperacionusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recuperacionusuario',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de Recuperacion', 'verbose_name_plural': 'Solicitudes de Recuperacion'},
        ),
        migrations.RemoveField(
            model_name='recuperacionusuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='recuperacionusuario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='recuperacionusuario',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='recuperacionusuario',
            name='recuperado',
            field=models.BooleanField(default=False, verbose_name='Recuperado'),
        ),
    ]
