# Generated by Django 5.0 on 2024-08-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0008_alter_recuperacionusuario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recuperacionusuario',
            name='user',
        ),
        migrations.AddField(
            model_name='recuperacionusuario',
            name='correo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menu.student_registration'),
        ),
    ]
