# Generated by Django 5.0 on 2024-08-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_remove_recuperacionusuario_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperacionusuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
    ]
