# Generated by Django 4.2 on 2025-05-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu', '0002_alter_carnetestudiantil_expiracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProcesada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_procesadas/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.student_registration')),
            ],
        ),
    ]
